/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./404.html",
    "./{admin,faq,galeri,harga,lokasi,kebijakan-privasi,syarat-ketentuan}/**/*.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#dee4e0",
        "surface-container": "#e9efec",
        "tertiary-fixed-dim": "#f0bd8b",
        "primary-container": "#0b3b2c",
        "on-tertiary-fixed": "#2c1600",
        "surface": "#f5fbf7",
        "primary-fixed": "#bdedd7",
        "surface-dim": "#d5dbd8",
        "inverse-surface": "#2c322f",
        "inverse-primary": "#a2d1bb",
        "on-secondary-container": "#006f66",
        "on-surface-variant": "#414944",
        "on-tertiary-fixed-variant": "#623f18",
        "inverse-on-surface": "#ecf2ee",
        "on-background": "#171d1b",
        "on-secondary": "#ffffff",
        "on-secondary-fixed-variant": "#005049",
        "surface-tint": "#3b6756",
        "on-primary-container": "#78a692",
        "on-primary-fixed-variant": "#224f3f",
        "tertiary-container": "#4c2c06",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#ffdcbd",
        "background": "#f5fbf7",
        "surface-variant": "#dee4e0",
        "secondary": "#006a61",
        "error": "#ba1a1a",
        "primary-fixed-dim": "#a2d1bb",
        "on-surface": "#171d1b",
        "outline-variant": "#c0c8c3",
        "on-error-container": "#93000a",
        "outline": "#717974",
        "surface-bright": "#f5fbf7",
        "on-tertiary-container": "#c29364",
        "secondary-fixed-dim": "#6bd8cb",
        "secondary-container": "#86f2e4",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#002116",
        "tertiary": "#301900",
        "surface-container-low": "#eff5f1",
        "on-tertiary": "#ffffff",
        "surface-container-high": "#e4eae6",
        "on-error": "#ffffff",
        "secondary-fixed": "#89f5e7",
        "primary": "#002419",
        "on-secondary-fixed": "#00201d",
        "error-container": "#ffdad6"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-desktop": "5rem",
        "margin": "1.25rem",
        "space-xs": "0.375rem",
        "space-lg": "2rem",
        "space-md": "1.25rem",
        "margin-tablet": "2.5rem",
        "gutter": "1.5rem",
        "space-sm": "0.75rem",
        "gutter-desktop": "2.5rem",
        "space-xl": "3.5rem"
      },
      fontFamily: {
        "headline-lg": ["Playfair Display", "serif"],
        "headline-md": ["Playfair Display", "serif"],
        "headline-sm": ["Playfair Display", "serif"],
        "display": ["Playfair Display", "serif"],
        "display-mobile": ["Playfair Display", "serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "label-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.1em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "600" }],
        "headline-sm": ["22px", { lineHeight: "30px", fontWeight: "600" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.06em", fontWeight: "600" }],
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "display-mobile": ["38px", { lineHeight: "44px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-md": ["28px", { lineHeight: "36px", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": ["30px", { lineHeight: "38px", fontWeight: "500" }],
        "display": ["56px", { lineHeight: "64px", letterSpacing: "-0.02em", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
